### ISSUE TITLE
编译不了报错

### ISSUE THREAD

**Issue by kanxue660** [tboox/vm86#1]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
xp和win10系统下，xmake编译，报错，如下，

Z:\vm86-master\src\vm86>xmake -P .
checking for the architecture ... x86
checking for the Microsoft Visual Studio (x86) version ... 2008
error: cannot get variable(VERSION) in vm86.config.h.in.

**Comment by waruqi** [comment]
你重拉下代码，然后更新到master版本xmake

然后再执行xmake编译试试

**Comment by kanxue660** [comment]
根据命令安装截图
![image](https://user-images.githubusercontent.com/9911566/71046940-de6f9900-2174-11ea-82cc-2de1760e4400.png)

测试结果，加参数P，还是老样子
![image](https://user-images.githubusercontent.com/9911566/71046990-0f4fce00-2175-11ea-83cb-a63c709c6c16.png)

不加参数截图
![image](https://user-images.githubusercontent.com/9911566/71047018-2b536f80-2175-11ea-8423-f58195c4af0c.png)

昨天不加 p参数，好像提示缺少tbox，但是不知道为何，安装过程好像没有下载下来

**Comment by waruqi** [comment]
跟-P 没有任何关系 不用加，老错误 你还是没重拉vm86代码

**Comment by waruqi** [comment]
跟-P 没有任何关系 不用加，看错误 你还是没重拉vm86代码 ，还有为啥不到vm86-master工程根目录执行，非得切到src里面去

**Comment by kanxue660** [comment]
原版本是16号下载，刚才下载了最新的vm86，编译过了，谢谢
